//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonDichVu
    {
        [Display(Name = "Mã chi tiết đơn dịch vụ")]
        public int ID_CTDonDV { get; set; }
        [Display(Name = "Mã đơn dịch vụ")]
        public int ID_DonDV { get; set; }
        [Display(Name = "Mã dịch vụ")]
        public int ID_DichVu { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public Nullable<int> ID_SP { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<decimal> DonGia { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> ThanhTien { get; set; }
        [Display(Name = "Thông số kỹ thuật")]
        public string ThongSoKyThuat { get; set; }

        public virtual DichVu DichVu { get; set; }
        public virtual DonDichVu DonDichVu { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}