//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietPhieuNhap
    {
        [Display(Name ="Mã chi tiết phiếu nhập")]
        public int ID_CTPhieuNhap { get; set; }
        [Display(Name = "Mã phiếu nhập")]
        public Nullable<int> ID_PhieuNhap { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public Nullable<int> ID_SP { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Đơn giá nhập")]
        public Nullable<decimal> DonGiaNhap { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
