//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDonHang
    {
        [Display(Name ="Mã chi tiết đơn hàng")]
        public int ID_CTDonHang { get; set; }
        [Display(Name = "Mã đơn hàng")]
        public int ID_DonHang { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public int ID_SP { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<decimal> DonGia { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
