//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatSan
    {
        [Display(Name = "Mã đặt sân")]
        public int ID_DatSan { get; set; }
        [Display(Name = "Mã khách hàng")]
        public Nullable<int> ID_KhachHang { get; set; }
        [Display(Name = "Mã sân cầu lông")]
        public int ID_San { get; set; }
        [Display(Name = "Ngày đặt")]
        public System.DateTime NgayDat { get; set; }
        [Display(Name = "Giờ bắt đầu")]
        public System.TimeSpan GioBatDau { get; set; }
        [Display(Name = "Giờ kết thúc")]
        public System.TimeSpan GioKetThuc { get; set; }
        [Display(Name = "Số giờ")]
        public Nullable<int> SoGio { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<decimal> TongTien { get; set; }
        [Display(Name = "Trạng thái")]
        public string TrangThai { get; set; }
        [Display(Name = "Tiền cọc")]
        public Nullable<decimal> TienCoc { get; set; }
        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        public virtual SanCauLong SanCauLong { get; set; }
    }
}