//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.ChiTietDonDichVus = new HashSet<ChiTietDonDichVu>();
        }
        [Display(Name = "Mã dịch vụ")]
        public int ID_DichVu { get; set; }
        [Display(Name = "Tên dịch vụ")]
        public string TenDichVu { get; set; }
        [Display(Name = "Loại dịch vụ")]
        public int ID_LoaiDV { get; set; }
        [Display(Name = "Đơn giá")]
        public decimal DonGia { get; set; }
        [Display(Name = "Thời gian thực hiện")]
        public Nullable<int> ThoiGianThucHien { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDichVu> ChiTietDonDichVus { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
    }
}