
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDichVu()
        {
            this.ChiTietDonDichVus = new HashSet<ChiTietDonDichVu>();
            this.LichSuTichDiems = new HashSet<LichSuTichDiem>();
        }
        [Display(Name = "Mã đơn dịch vụ")]
        public int ID_DonDV { get; set; }
        [Display(Name = "Mã khách hàng")]
        public Nullable<int> ID_KhachHang { get; set; }
        [Display(Name = "Tên khách hàng")]
        public string TenKhach { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Ngày nhận")]
        public Nullable<System.DateTime> NgayNhan { get; set; }
        [Display(Name = "Ngày trả")]
        public Nullable<System.DateTime> NgayTra { get; set; }
        [Display(Name = "Tổng tiền")]
        public Nullable<decimal> TongTien { get; set; }
        [Display(Name = "Trạng thái")]
        public string TrangThai { get; set; }
        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDichVu> ChiTietDonDichVus { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTichDiem> LichSuTichDiems { get; set; }
    }
}
