//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GioHangChiTiet
    {
        [Display(Name ="Mã chi tiết giỏ hàng")]
        public int ID_CTGH { get; set; }
        [Display(Name = "Mã giỏ hàng")]
        public int ID_GioHang { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public int ID_SP { get; set; }
        [Display(Name = "Số lượng")]
        public int SoLuong { get; set; }
        [Display(Name = "Đơn giá")]
        public decimal DonGia { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual GioHang GioHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
