//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GioHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GioHang()
        {
            this.GioHangChiTiets = new HashSet<GioHangChiTiet>();
        }
        [Display(Name ="Mã giỏ hàng")]
        public int ID_GioHang { get; set; }
        [Display(Name = "Mã khách hàng")]
        public Nullable<int> ID_KhachHang { get; set; }
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> NgayTao { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name ="Tổng tiền")]
        public decimal? TongTien { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangChiTiet> GioHangChiTiets { get; set; }
    }
}
