//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HoiVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoiVien()
        {
            this.LichSuTichDiems = new HashSet<LichSuTichDiem>();
        }
        [Display(Name ="Mã hội viên")]
        public int ID_HoiVien { get; set; }
        [Display(Name = "Mã khách hàng")]
        public int ID_KhachHang { get; set; }
        [Display(Name = "Mã thẻ")]
        public string MaThe { get; set; }
        [Display(Name = "Ngày đăng ký")]
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        [Display(Name = "Ngày hết hạn")]
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        [Display(Name = "Cấp độ")]
        public string CapDo { get; set; }
        [Display(Name = "Điểm tích lũy")]
        public Nullable<int> DiemTichLuy { get; set; }
        [Display(Name = "Ưu đãi")]
        public Nullable<decimal> UuDai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTichDiem> LichSuTichDiems { get; set; }
    }
}
