//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichSuTichDiem
    {
        [Display(Name = "Mã lịch sử tích điểm")]
        public int ID_LichSu { get; set; }
        [Display(Name = "Mã hội viên")]
        public int ID_HoiVien { get; set; }
        [Display(Name = "Mã đơn hàng")]
        public Nullable<int> ID_DonHang { get; set; }
        [Display(Name = "Mã đơn dịch vụ")]
        public Nullable<int> ID_DonDV { get; set; }
        [Display(Name = "Điểm cộng")]
        public Nullable<int> DiemCong { get; set; }
        [Display(Name = "Điểm trừ")]
        public Nullable<int> DiemTru { get; set; }
        [Display(Name = "Lý do")]
        public string LyDo { get; set; }
        [Display(Name = "Ngày tích điểm")]
        public Nullable<System.DateTime> NgayTichDiem { get; set; }

        public virtual DonDichVu DonDichVu { get; set; }
        public virtual DonHang DonHang { get; set; }
        public virtual HoiVien HoiVien { get; set; }
    }
}