//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QuanTri
    {
        [Display(Name = "Mã quản trị")]
        public int ID_QT { get; set; }
        [Display(Name = "Tài khoản")]
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }
        [Display(Name = "Vai trò")]
        public string VaiTro { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
    }
}