//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanCauLong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanCauLong()
        {
            this.DatSans = new HashSet<DatSan>();
        }
        [Display(Name ="Mã sân cầu lông")]
        public int ID_San { get; set; }
        [Display(Name = "Tên sân cầu lông")]
        public string TenSan { get; set; }
        [Display(Name = "Loại sân")]
        public string LoaiSan { get; set; }
        [Display(Name = "Giá thuê theo giờ")]
        public decimal GiaThueTheoGio { get; set; }
        [Display(Name = "Trạng thái")]
        public string TrangThai { get; set; }
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatSan> DatSans { get; set; }
    }
}
