//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int ID_ThanhToan { get; set; }
        public Nullable<int> ID_DonHang { get; set; }
        public string PhuongThuc { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
