//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NVD_2210900016_DATN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhToan
    {
        [Display(Name = "Mã thanh toán")]
        public int ID_ThanhToan { get; set; }
        [Display(Name = "Mã đơn hàng")]
        public Nullable<int> ID_DonHang { get; set; }
        [Display(Name = "Phương thức")]
        public string PhuongThuc { get; set; }
        [Display(Name = "Trạng thái")]
        public string TrangThai { get; set; }
        [Display(Name = "Ngày thanh toán")]
        public Nullable<System.DateTime> NgayThanhToan { get; set; }

        public virtual DonHang DonHang { get; set; }
    }
}